### PR TITLE
Added Esp infos to status page

### PR DESCRIPTION
**Pull request by wib100**

### CODE REVIEW

**Comment by zivillian** [comment]
Thanks for this PR!

I may have a few adjustments - do you prefer comments in a review, or should I just push my modifications?

**Comment by wib100** [comment]
Hi,
just push it.

Thanks!

**Comment by ReneHezser** [comment]
Thanks a lot. Looking good and the OTA update did succeed :-)

**Comment by wib100** [comment]
Great! Thx!

**Pull request merged**
